-- TABLE & SEQUENCE DROP
DROP SEQUENCE BOOK_SEQ;
DROP SEQUENCE fNUM_SEQ;
DROP TABLE BOOK;
DROP TABLE FILEBOARD;
DROP TABLE CUSTOMER;

-- TABLE & SEQUENCE CREATE
CREATE TABLE CUSTOMER(
    cID VARCHAR2(50) PRIMARY KEY,
    cPW VARCHAR2(50) NOT NULL,
    cNAME VARCHAR2(50) NOT NULL,
    cTEL VARCHAR2(50),
    cEMAIL VARCHAR2(50),
    cADDRESS VARCHAR2(250),
    cGENDER VARCHAR2(10),
    cBIRTH DATE,
    cRDATE DATE DEFAULT SYSDATE NOT NULL
);
CREATE TABLE FILEBOARD(
    fNUM NUMBER(7) PRIMARY KEY,
    cID VARCHAR2(50) REFERENCES CUSTOMER(cID),
    fSUBJECT VARCHAR2(250) NOT NULL,
    fCONTENT CLOB,
    fFILENAME VARCHAR2(50),
    fPW VARCHAR2(50) NOT NULL,
    fHIT NUMBER(7) DEFAULT 0 NOT NULL,
    fREF NUMBER(7) NOT NULL,
    fRE_STEP NUMBER(7) NOT NULL,
    fRE_LEVEL NUMBER(1) NOT NULL,
    fIP VARCHAR2(50) NOT NULL,
    fRDATE DATE DEFAULT SYSDATE NOT NULL    
);

CREATE TABLE BOOK(
    bID NUMBER(7,0) PRIMARY KEY,
    bTITLE VARCHAR2(50) NOT NULL,
    bPRICE NUMBER(7) NOT NULL,
    bIMAGE1 VARCHAR2(50) DEFAULT 'onImg.png' NOT NULL,
    bIMAGE2 VARCHAR2(50) DEFAULT 'NOTHING.JPG' NOT NULL,
    bCONTENT VARCHAR2(4000),
    bDISCOUNT NUMBER(3) NOT NULL,
    bRDATE DATE DEFAULT SYSDATE NOT NULL
);

CREATE SEQUENCE fNUM_SEQ MAXVALUE 9999999 NOCACHE NOCYCLE;
CREATE SEQUENCE BOOK_SEQ MAXVALUE 9999999 NOCACHE NOCYCLE;
-- 인덱스나 뷰 생성