-- TABLE & SEQUENCE DROP
DROP TABLE MVC_BOARD;
DROP SEQUENCE MVC_BOARD_SEQ;
-- TABLE & SEQUENCE CREATE
CREATE TABLE MVC_BOARD(
    BID NUMBER(6) PRIMARY KEY,
    BNAME VARCHAR2(50) NOT NULL,
    BTITLE VARCHAR2(100) NOT NULL,
    BCONTENT VARCHAR2(1000),
    BDATE DATE DEFAULT SYSDATE NOT NULL,
    BHIT NUMBER(6) DEFAULT 0 NOT NULL,
    BGROUP NUMBER(6) NOT NULL,
    BSTEP NUMBER(3) NOT NULL,
    BINDENT NUMBER(3) NOT NULL,
    BIP VARCHAR2(20) NOT NULL
);
CREATE SEQUENCE MVC_BOARD_SEQ MAXVALUE 999999 NOCACHE NOCYCLE;
    
-- DUMMY DATA
SELECT * FROM MVC_BOARD;
INSERT INTO MVC_BOARD (BID, BNAME, BTITLE, BCONTENT, BGROUP, BSTEP, BINDENT, BIP)
    VALUES (MVC_BOARD_SEQ.NEXTVAL, '홍길동', '제목', '본문', MVC_BOARD_SEQ.CURRVAL, 0, 0, '192.1.1.1');
INSERT INTO MVC_BOARD (BID, BNAME, BTITLE, BCONTENT, BGROUP, BSTEP, BINDENT, BIP)
    VALUES (MVC_BOARD_SEQ.NEXTVAL, '김두', '소나기', '비', MVC_BOARD_SEQ.CURRVAL, 0, 0, '192.1.1.1');
-- 2번 글 답글
INSERT INTO MVC_BOARD (BID, BNAME, BTITLE, BCONTENT, BGROUP, BSTEP, BINDENT, BIP)
    VALUES (MVC_BOARD_SEQ.NEXTVAL, '마동석', '답변글', '제곧내', 2, 1, 1, '192.1.1.4');
    
-- DAO에 들어갈 QUERY
-- 1. 글목록 (STARTROW ~ ENDROW)
SELECT * FROM MVC_BOARD ORDER BY BGROUP DESC, BSTEP;
SELECT * FROM (SELECT ROWNUM RN, A.* FROM (SELECT * FROM MVC_BOARD ORDER BY BGROUP DESC, BSTEP) A) WHERE RN BETWEEN 1 AND 10;
-- 2. 전체 글 갯수
SELECT COUNT(*) FROM MVC_BOARD;
-- 3. 원글 쓰기
INSERT INTO MVC_BOARD (BID, BNAME, BTITLE, BCONTENT, BGROUP, BSTEP, BINDENT, BIP)
    VALUES (MVC_BOARD_SEQ.NEXTVAL, '용묭', '프라이탁', '삿당', MVC_BOARD_SEQ.CURRVAL, 0, 0, '192.1.1.3');
-- 4. BID로 조회수 1 올리기
UPDATE MVC_BOARD SET BHIT = BHIT+1 WHERE BID=1;
-- 5. BID로 DTO 가져오기 (글 상세보기, 글 수정 VIEW, 답변글 VIEW)
SELECT * FROM MVC_BOARD WHERE BID=1;
-- 6. 글 수정
UPDATE MVC_BOARD SET BNAME='김나나',
                    BTITLE='제목변경',
                    BCONTENT='본문변경'
                WHERE BID='1';
-- 7. 글 삭제
DELETE FROM MVC_BOARD WHERE BID=4; 
-- 8. 답변글 저장 전 작업 (STEP 1 : 예시에서는 2번글의 답변)
UPDATE MVC_BOARD SET BSTEP = BSTEP+1
    WHERE BGROUP = 2 AND BSTEP > 0;
-- 8. 답변글 쓰기
INSERT INTO MVC_BOARD (BID, BNAME, BTITLE, BCONTENT, BGROUP, BSTEP, BINDENT, BIP)
    VALUES (MVC_BOARD_SEQ.NEXTVAL, '김동생', '주룩주룩', NULL, 2, 1, 1, '126.1.1.1');
COMMIT;