DROP TABLE BD;

CREATE TABLE BD(
    NUM NUMBER PRIMARY KEY,
    WRITER VARCHAR2(30) NOT NULL,
    SUBJECT VARCHAR2(50) NOT NULL,
    CONTENT CLOB NOT NULL,
    EMAIL VARCHAR2(30),
    PW VARCHAR2(20) NOT NULL,
    READCOUNT NUMBER DEFAULT 0,
    IP VARCHAR2(20) NOT NULL,
    RDATE DATE NOT NULL
);

CREATE SEQUENCE NUM_SEQ
    INCREMENT BY 1
    START WITH 1
    MINVALUE 1
    NOCYCLE
    NOCACHE
    ORDER;
    

-- 1. 글 갯수
SELECT COUNT(*) FROM BD;
-- 2. 글 목록
SELECT * FROM BD;
-- 3. 글 목록 (TOPN구문)
SELECT ROWNUM RN, A. * FROM (SELECT * FROM BD ORDER BY NUM DESC) A;
SELECT * FROM (SELECT ROWNUM RN, A. * FROM (SELECT * FROM BD ORDER BY NUM DESC) A) WHERE RN BETWEEN 1 AND 10;
-- 4. 글 쓰기
INSERT INTO BD (NUM, WRITER, SUBJECT, CONTENT, EMAIL, PW, IP, RDATE) 
    VALUES (NUM_SEQ.NEXTVAL, '김수한무', '거북이', '두루미', NULL, '111', '192.0.0.2', SYSDATE);
-- 5. 글 번호로 글 상세 보기 (내용)
SELECT * FROM BD WHERE NUM=2;
-- 6. 조회수
UPDATE BD SET READCOUNT = READCOUNT + 1 WHERE NUM=2;
-- 7. 글 수정
UPDATE BD SET SUBJECT = '엄마곰',
                CONTENT = '아빠곰',
                EMAIL = 'gom@gmail.com',
                PW = '112',
                IP='192.0.0.3'
            WHERE NUM=2;
-- 8. 글 삭제
DELETE FROM BD WHERE NUM=2 AND PW='112';
-- 데이터 조작
INSERT INTO BD (NUM, WRITER, SUBJECT, CONTENT, EMAIL, PW, READCOUNT, IP, RDATE) 
    VALUES (NUM_SEQ.NEXTVAL, '김수한무', '거북이', '두루미', NULL, '111', 0, '192.0.0.2', SYSDATE);
    
COMMIT;