-- [XII] Transaction 명령어: COMMIT(트랜잭션 반영) / ROLLBACK(트랜잭션 취소) / SAVEPOINT(트랜잭션 분할)

DROP TABLE DEPT01;
CREATE TABLE DEPT01 AS SELECT * FROM DEPT;
COMMIT;
------ 새로운 트랜잭션 시작
SELECT * FROM DEPT01;
DELETE FROM DEPT01 WHERE DEPTNO=20;
DELETE FROM DEPT01 WHERE DEPTNO=30;
ROLLBACK;
------
SELECT 