SELECT * FROM EMP; -- 실행하고자 하는 SQL문 블럭 잡고 alt+x로 실행 EX2_oracle.jsp

-- ex3.jsp
SELECT * FROM DEPT;
SELECT * FROM EMP WHERE DEPTNO LIKE '%'||'';
DELETE FROM DEPT WHERE DEPTNO LIKE '51';
COMMIT;

SELECT * FROM EMP WHERE ENAME LIKE 'SCOTT';