DROP TABLE HOST_REPLY;
DROP TABLE GUEST_RESERVATION;
DROP TABLE GUEST_REVIEW;
DROP TABLE MEMBER_GUEST;
DROP TABLE GUEST_REVIEW;
DROP TABLE HOST_CAMPSITE;
DROP TABLE MEMBER_HOST;
DROP TABLE CAMPLAY_ADMIN;

CREATE TABLE MEMBER_GUEST (
    gID VARCHAR2(15) PRIMARY KEY,
    gEMAIL VARCHAR2(30) NOT NULL,
    gPW VARCHAR2(40)NOT NULL,
    gNAME VARCHAR2(30) NOT NULL,
    gNICK VARCHAR2(30) NOT NULL,
    gTEL VARCHAR2(15) NOT NULL,
    gPHOTO VARCHAR2(100) NOT NULL
);

CREATE TABLE GUEST_REVIEW (
    rNO NUMBER(6) PRIMARY KEY,
    gID VARCHAR2(15) NOT NULL,
    rTITLE VARCHAR2(255) NOT NULL,
    rCONTENT CLOB NOT NULL,
    rRDATE DATE NOT NULL,
    rIP VARCHAR2(30) NOT NULL,
    rMAINPHOTO VARCHAR2(255),
    rPHOTO1 VARCHAR2(255),
    rPHOTO2 VARCHAR2(255),
    rPHOTO3 VARCHAR2(255),
    FOREIGN KEY (gID) REFERENCES MEMBER_GUEST(gID)
);

CREATE TABLE CAMPLAY_ADMIN (
    aID VARCHAR2(15) PRIMARY KEY,
    aPW VARCHAR2(40) NOT NULL,
    aNAME VARCHAR2(30) NOT NULL
);

CREATE TABLE MEMBER_HOST (
    hID VARCHAR2(15) PRIMARY KEY,
    hEMAIL VARCHAR2(30) NOT NULL,
    hPW VARCHAR2(40) NOT NULL,
    hNAME VARCHAR2(30) NOT NULL,
    hTEL VARCHAR2(15) NOT NULL,
    hBISNUM VARCHAR2(10) NOT NULL,
    hBISPIC VARCHAR2(50) NOT NULL,
    hACCOUNT VARCHAR2(20) NOT NULL,
    hACCPIC VARCHAR2(50) NOT NULL,
    hPHOTO VARCHAR2(100) NOT NULL
);

CREATE TABLE HOST_CAMPSITE (
    cNO NUMBER(5) PRIMARY KEY,
    cNAME VARCHAR2(50) NOT NULL,
    cDESCRIPTION VARCHAR2(255) NOT NULL,
    cADDRESS VARCHAR2(255) NOT NULL,
    cPRICE NUMBER(7) NOT NULL,
    hID VARCHAR2(15) NOT NULL,
    cMAINPHOTO VARCHAR2(255) NOT NULL,
    cPHOTO1 VARCHAR2(255) NOT NULL,
    cPHOTO2 VARCHAR2(255) NOT NULL,
    cPHOTO3 VARCHAR2(255) NOT NULL,
    cPHOTO4 VARCHAR2(255) NOT NULL,
    cPHOTO5 VARCHAR2(255) NOT NULL,
    FOREIGN KEY (hID) REFERENCES MEMBER_HOST (hID)
);

CREATE TABLE GUEST_RESERVATION(
    reNO NUMBER(5) PRIMARY KEY,
    reDAYFROM DATE NOT NULL,
    reDAYTO DATE NOT NULL,
    gID VARCHAR2(15) NOT NULL,
    cNO NUMBER(5) NOT NULL,
    FOREIGN KEY (gID) REFERENCES MEMBER_GUEST (gID),
    FOREIGN KEY (cNO) REFERENCES HOST_CAMPSITE (cNO)
);

CREATE TABLE HOST_REPLY(
    repNO NUMBER(6) PRIMARY KEY,
    repCONTENT VARCHAR2(400) NOT NULL,
    rNO NUMBER(6) NOT NULL,
    hID VARCHAR2(15) NOT NULL,
    repIP VARCHAR2(30) NOT NULL,
    FOREIGN KEY (rNO) REFERENCES GUEST_REVIEW (rNO),
    FOREIGN KEY (hID) REFERENCES MEMBER_HOST (hID)
);

