-- 1
INSERT INTO DEPT VALUES (50, 'IT', 'SEOUL');
SELECT * FROM DEPT;
COMMIT;
-- 2
SELECT COUNT(*) CNT FROM DEPT WHERE DEPTNO=99;
INSERT INTO DEPT VALUES (60, 'IT', 'SEOUL');

--update
UPDATE DEPT SET DNAME='MARKETING', LOC='INCHON'
    WHERE DEPTNO=52;
    
SELECT COUNT(*) CNT FROM DEPT WHERE DEPTNO=99;

-- DELETE
DELETE FROM DEPT WHERE DEPTNO=52;
COMMIT;