DROP TABLE MVC_MEMBER;

CREATE TABLE MVC_MEMBER(
    MID VARCHAR2(30) PRIMARY KEY,
    MPW VARCHAR2(30) NOT NULL,
    MNAME VARCHAR2(30) NOT NULL,
    MEMAIL VARCHAR2(30) NOT NULL,
    MPHOTO VARCHAR2(30),
    MBIRTH DATE,
    MADDRESS VARCHAR2(300),
    MRDATE DATE DEFAULT SYSDATE
);

-- id 중복체크
SELECT COUNT(*) FROM MVC_MEMBER WHERE MID='aaa';

-- join
INSERT INTO MVC_MEMBER (MID, MPW, MNAME, MEMAIL, MPHOTO, MBIRTH, MADDRESS)
    VALUES ('aaa', '111', '홍길동', 'hong@gmai.com', NULL, TO_DATE('1995-08-02', 'YYYY-MM-DD'), '서울시');

-- login check 
SELECT * FROM MVC_MEMBER WHERE MID = 'aaa' AND MPW='111';

-- mid로 memberDto 가져오기
SELECT * FROM MVC_MEMBER WHERE MID='aaa';